### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by axlrose** [walkingsky/luci-wifdog#1]
使用的是openwrt最新git仓库
放到自己做的feeds里面，编译提示 cp 出错，没有dist目录
查看src目录还有build下面的，的确没这个目录

**Comment by walkingsky** [comment]
确认 make menuconfig 勾选上了 该选项。
默认放置位置 建议放到 pacakage 目录里！

**Comment by walkingsky** [comment]
新的分之中有解决
