### ISSUE TITLE
最新openwrt trunk编译不过去

### ISSUE THREAD

**Issue by xjgan** [walkingsky/luci-wifdog#2]
在最新的openwrt trunk代码下编译不过去：
make[4]: Entering directory `/home64/projects/jiasudu/router/4imp/openwrt-trunk/build_dir/target-mipsel_24kec+dsp_uClibc-0.9.33.2/luci/applications/luci-wifidog'
Makefile:4: ../../build/config.mk: No such file or directory
Makefile:5: ../../build/module.mk: No such file or directory
luci下面根本就没有config.mk, 整个代码包都没有module.mk

**Comment by walkingsky** [comment]
是否没有进行过feed更新？

我会做下测试的

**Comment by walkingsky** [comment]
新的分之中有解决
