### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by xosadmin** [walkingsky/luci-wifdog#4]
在lede下编译提示这个：
make[1]: Entering directory '/home/xosadmin/lede'
make[1]: *** No rule to make target 'package/lean/luci-app-wifidog/install'.  Stop.
make[1]: Leaving directory '/home/xosadmin/lede'
make: *** [/home/xosadmin/lede/include/toplevel.mk:218: package/lean/luci-app-wifidog/install] Error 2

请问这个该如何解决呢？

**Comment by walkingsky** [comment]
新进根据lede重新进行了Makefile的适配，测试可以通过编译
