### ISSUE TITLE
o19-x64出错

### ISSUE THREAD

**Issue by shangyanjin** [walkingsky/luci-wifdog#5]
/usr/lib/lua/luci/dispatcher.lua:469: Failed to execute cbi dispatcher target for entry '/admin/services/wifidog'.
The called action terminated with an exception:
/usr/lib/lua/luci/model/cbi/wifidog/wifidog_cfg.lua:84: attempt to call field 'arptable' (a nil value)
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:469: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:121: in function </usr/lib/lua/luci/dispatcher.lua:120>

**Comment by walkingsky** [comment]
参考：https://bbs.hassbian.com/thread-6387-1-1.html

编辑vim /usr/lib/lua/luci/model/cbi/s-sr/client.lua将local arp_table = luci.sys.net.arptable() or {}修改为local arp_table = luci.ip.neighbors()

**Comment by walkingsky** [comment]
closed on 76ad568776479e3d7ccc2deb928f24ab7e00ddc4
